/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An array of stages. A stage can either be a string name corresponding to a script or a config object.
 */
export type LifecycleStagesList = (string | LifecycleStageConfig)[];

/**
 * A configuration object for a project using the Cyclist build lifecycles tool.
 */
export interface CyclistConfiguration {
  /**
   * A set of build lifecycles available to this project.
   */
  lifecycles?: {
    [k: string]: LifecycleStagesList | LifecycleConfig;
  };
  [k: string]: unknown;
}
export interface LifecycleStageConfig {
  /**
   * The name of the stage that can be referenced using the CLI
   */
  name: string;
  /**
   * An array of tasks to run in this stage. If not provided the stage name is used as the default task
   */
  tasks?: (string | LifecycleTaskConfig)[];
  /**
   * Whether all the tasks in this stage should be run in parallel to each other
   */
  parallel?: boolean;
  /**
   * Sets the default outputMode on tasks within this stage.
   */
  outputMode?: "stream" | "batch" | "ignore";
  [k: string]: unknown;
}
export interface LifecycleTaskConfig {
  /**
   * The script to run. This must correspond to the name of a script in the package being worked upon.
   */
  script: string;
  /**
   * How stdio output from this task should be handled.
   */
  outputMode?: "stream" | "batch" | "ignore";
  [k: string]: unknown;
}
export interface LifecycleConfig {
  stages: LifecycleStagesList;
  [k: string]: unknown;
}
